### ISSUE TITLE
ERROR: 'Rados' object has no attribute 'pool_lookup'

### ISSUE THREAD

**Issue by alsrt** [swiftgist/lrbd#2]
In the test rbd process, found lrbd will go to seek for ool_lookup , might throw an exception (error:'Rados'object has no attribute'pool_lookup''pool_lookup'), I in the official website of the CEPH also not find the pool lookup,please tell me this error how to solve

my os is centos7
/home/lrbd/lrbd -o

**Comment by swiftgist** [comment]
It's on the hammer branch.
https://github.com/ceph/ceph/blob/hammer/src/pybind/rados.py  Not sure who
updates the CentOS 7 repos, though.

**Comment by alsrt** [comment]
Thanks, I changed the Fedra system, the installation is normal，but Error executing lrbd:

root@igw1 home]#  lrbd
targetcli /backstores/rbd create name=vdisk003 dev=/dev/rbd/rbd/vdisk003
No such path /backstores/rbd ?  this error how to solve?

**Comment by alsrt** [comment]
Thanks, I changed the Fedra system, the installation is normal，but Error executing lrbd:
root@igw1 home]#  lrbd
targetcli /backstores/rbd create name=vdisk003 dev=/dev/rbd/rbd/vdisk003
No such path /backstores/rbd ?  this error how to solve?

[root@igw1 ~]# lrbd -v
INFO: No configuration object lrbd.conf in pool data
INFO: No configuration object lrbd.conf in pool metadata
INFO: No configuration object lrbd.conf in pool .rgw.root
INFO: No configuration object lrbd.conf in pool .rgw.control
INFO: No configuration object lrbd.conf in pool .rgw
INFO: No configuration object lrbd.conf in pool .rgw.gc
INFO: No configuration object lrbd.conf in pool .users.uid
INFO: No configuration object lrbd.conf in pool .users
INFO: No configuration object lrbd.conf in pool .users.swift
INFO: No configuration object lrbd.conf in pool .rgw.buckets
INFO: No configuration object lrbd.conf in pool .rgw.buckets.index
INFO: No configuration object lrbd.conf in pool .rgw.buckets.extra
INFO: No configuration object lrbd.conf in pool .log
INFO: No configuration object lrbd.conf in pool .intent-log
INFO: No configuration object lrbd.conf in pool .usage
INFO: No configuration object lrbd.conf in pool .users.email
INFO: No configuration object lrbd.conf in pool datastore
INFO: No configuration object lrbd.conf in pool testdb
INFO: No configuration object lrbd.conf in pool datastore2
INFO: No configuration object lrbd.conf in pool datastore3
INFO: No configuration object lrbd.conf in pool swimming
targetcli /backstores/rbd create name=vdisk003 dev=/dev/rbd/rbd/vdisk003
No such path /backstores/rbd

**Comment by mikechristie** [comment]
Only SUSE ships the target_core_rbd module which provides the rbd backstore.

Upstream, we are working on modifying the block layer to support what is needed so the krbd driver can be used with targetcli's iblock backstore.
